# Setup
title:               CMPT732
tagline:             'Group project NYC CAB Analysis'
description:         
url:                 https://apphiawang.github.io/
baseurl:             /cmpt732_nyc_cab
paginate:            5
permalink:           pretty
excerpt_separator: <!--more-->


# Gems
# About/contact
author:
  name:              Yanfei Wang, Yiwen Wang, Yucheng Gao, Axida
  url:               https://github.com/apphiaWang/cmpt732_nyc_cab
  email:             yanfei_wang@sfu.ca

plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
